/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EC } from "./EC";
export type { GeneralElection } from "./GeneralElection";

export { EC__factory } from "./factories/EC__factory";
export { GeneralElection__factory } from "./factories/GeneralElection__factory";
